"""Generated public release metadata. Edit RELEASE.env and run generate_release_files.py."""
PUBLIC_VERSION = "Kiosk 2.3"
PUBLIC_VERSION_NUMBER = "2.3"
APP_VERSION = "2.3.0"
RELEASE_DATE = "2026-10-02"
