"""Generated release metadata. Do not edit directly; edit RELEASE.env and run generate_release_files.py."""
PUBLIC_VERSION = "Kiosk 2.2"
PUBLIC_VERSION_NUMBER = "2.2"
DESKTOP_RELEASE_VERSION = "1.27.15"
RELEASE_DATE = "2026-08-08"
INTERNAL_VERSION = "v30"
RELEASE_CHANNEL = "public"
RELEASE_LABEL = "v30 Public"
IMAGE_BASENAME = "ai-case-sorter-kiosk-v2.2-v30-public"
ARCHIVE_BASENAME = "AI-Case-Sorter-Kiosk-v2.2-Internal-v30-Public-Ubuntu-pi-gen"
